CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN,
    email VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255)
);
INSERT INTO users(
	id, active, email, password, username)
	VALUES  (1,false,'edisonenc1409@gmail.com','lamismadeayer','edisonenc1409');
