name: CI/CD Spring Boot + Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Add this line # Add this line
      - name: Compilar y testear con Maven
        run: mvn test -Dspring.profiles.active=ci #mvn clean verify
      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Set image version
        run: echo "IMAGE_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Construir imagen Docker
        run: |
          docker build -t java-docker-cresa edisonenc1409/repositorio-credito:${IMAGE_VERSION} .
          docker push edisonenc1409/repositorio-credito:${IMAGE_VERSION}
